### ISSUE TITLE
pointer being freed was not allocated

### ISSUE THREAD

**Issue by yamayamasa** [ProteinDF/ProteinDF#9]
平野先生
テキストを参考にProteinDF_bridge, ProteinDF_pytools, ProteinDFをインストール後に、fl_Input等のディレクトリを作成し、サンプルプログラムを置きProteinDFを実行しましたところ以下のようなエラーが発生しました。（なお、インストール（MPIを使わない設定にてインストールしました）時はいずれもエラーは発生していないように思われます。）UNIXにはある程度は慣れておりますが、このような場合に対応できる程の技術は持ち合わせておりません。PATH設定や環境変数設定等の単純な間違いによるものかより複雑な原因によるものかさえ自分では分かりません。お手数をおかけしますが何らかのアドバイスを頂けますと幸いです。よろしくお願い致します。

MacBook-Pro:fl_Input user$ PDF.x
PDF.x(5468) malloc: *** error for object 0x7fff7dd04570: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by hiracchi** [comment]
ご不便をおかけしてすみません。

入力ファイル(fl_Userinput)と、もし出力(fl_Out_Std)があれば添付していただけないでしょうか。
よろしくお願い致します。

**Comment by yamayamasa** [comment]
お返事いただきありがとうございます。fl_Userinputを添付致します。fl_Out_Std他その他ファイルは出力されていないようです。特に急いではおりませんので、お手隙のときによろしくお願い致します。fl_Userinputは、他のページ上にありますProteinDFUsersManual.pdfの４章クイックスタートp20の入力ファイルをそのままコピーしました。

**Comment by hiracchi** [comment]
すみません。それでは実行環境ならびにビルド環境(configureの出力、config.log、makeの出力など)を教えていただけないでしょうか。
よろしくお願い致します。

**Comment by yamayamasa** [comment]
かなり古い環境ですが、BacBook Pro, 15-inch, Mid 2012, 2.3Ghz Intel Core i7, 8GB OSX 10.8.2です。ビルド時のログファイルを添付致します。（初回のビルド時のものが上書きされてしまっているものもあるかもしれません。）よろしくお願い致します。

**Comment by hiracchi** [comment]
ログが無いようですが、もしMacでしたら(+homebrewをお使いでしたら)
`brew tap hiracchi/proteindf && brew install proteindf`
を試してみてください。
https://github.com/hiracchi/homebrew-ProteinDF
よろしくお願いします。

**Comment by yamayamasa** [comment]
お忙しいところ、いろいろとどうもありがとうございます。新たにbrewを入れようとしましたが、すでにfinkを入れており、どうやら混ぜない方がよいという記述があちこちにあるようです。今試しているMacではなく、他のMacにbrewを入れて実行してみようと考えています。その結果は連絡致しますので、何かありましたらまたよろしくお願い致します。
